(defpackage #:loom/feature/terminal
  (:documentation "Terminal session management and terminal screen state.")
  (:use #:cl
        #:loom
        #:loom/application
        #:loom/feature/window)
  (:export
   #:terminal-screen
   #:terminal-screen-p
   #:terminal-screen-width
   #:terminal-screen-height
   #:terminal-screen-cursor-row
   #:terminal-screen-cursor-column
   #:make-terminal-screen
   #:terminal-screen-feed
   #:terminal-screen-text
   #:terminal-screen-resize
   #:terminal-session
   #:terminal-session-p
   #:terminal-session-name
   #:terminal-session-program
   #:terminal-session-args
   #:terminal-session-directory
   #:terminal-session-buffer
   #:terminal-session-pty
   #:terminal-session-raw-output
   #:terminal-session-alive-p
   #:terminal-session-exit-code
   #:terminal-session-screen
   #:terminal-session-output
   #:terminal-session-feed-output
   #:terminal-session-for-buffer
   #:start-terminal-session
   #:terminal-session-poll
   #:terminal-session-send
   #:terminal-session-resize
   #:stop-terminal-session
   #:poll-terminal-sessions
   #:resize-terminal-sessions
   #:terminal-input-event-p
   #:terminal-handle-key-event
   #:terminal
   #:terminal-stop))
